# To create the environment:
# #########################
# conda env create -f conda-env_NOCOS-RIDGING.yml
#    To update if yml-file has changed:
#    conda env update --file conda-env_NOCOS-RIDGING.yml --prune 
# To use the environment:
# ######################
# conda activate ridgingNOCOS
name: ridgingNOCOS
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - xarray
  - pyyaml
  - dask        # for xarray
  - netCDF4     # for xarray
  - bottleneck  # for xarray
